import { 
    FaBeerMugEmpty, 
    FaHouse, 
    FaBullseye, 
    FaProductHunt, 
    FaCircleQuestion, 
    FaCircleUser,
    FaUserSecret,
    FaWrench,
    FaUserTie,
    FaBoltLightning,
    FaBurger,
    FaBars,
    FaBasketShopping, 
    FaPhone,
    FaClock,
    FaLocationDot,

} from 'react-icons/fa6';

export const icons = {
    'FaBeerMugEmpty ' : <FaBeerMugEmpty />,
    'FaHouse' : <FaHouse />,
    'FaBullseye' : <FaBullseye />,
    'FaProductHunt' : <FaProductHunt />,
    'FaCircleQuestion' : <FaCircleQuestion />,
    'FaCircleUser' : <FaCircleUser />,
    'FaUserSecret' : <FaUserSecret />,
    'FaWrench' : <FaWrench  />,
    'FaUserTie' : <FaUserTie />,
    'FaBoltLightning' : <FaBoltLightning  />,
    'FaBurger' : <FaBurger />,
    'FaBars' : <FaBars />,
    'FaBasketShopping' : <FaBasketShopping />,
    'FaPhone' : <FaPhone />,
    'FaClock' : <FaClock />,
    'FaLocationDot' : <FaLocationDot />,
};
